### PR TITLE
changed intl version

### PR DESCRIPTION
**Pull request by germinator1512**

### CODE REVIEW

**Comment by mjablecnik** [comment]
What is reason of this change?

**Comment by germinator1512** [comment]
otherwise i get unsolvable dependency constraints on flutter version 3.22, as newer packages depend on intl version 0.19

**Comment by mjablecnik** [comment]
I think it should be solved by command: 
`flutter pub upgrade`
Did you try to run this command?

**Comment by germinator1512** [comment]
grafik
grafik
I can't upgrade because of the constraint to  0.18

**Comment by mjablecnik** [comment]
And when you run command: `flutter pub upgrade`?

**Comment by germinator1512** [comment]
grafik
same thing.. why don't you just accept the PR, it works, I tried it :)

**Comment by mjablecnik** [comment]
> why don't you just accept the PR, it works, I tried it :)

I have already experience with some MRs which didn't work.. :)

**Pull request merged**
